#!/usr/bin/env bash
set -euo pipefail

repository_root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ "$#" -ne 0 ]; then
    echo "usage: bash ./test.sh" >&2
    exit 2
fi

export PYTHONDONTWRITEBYTECODE=1
export PYTHONPATH="${repository_root}${PYTHONPATH:+:${PYTHONPATH}}"
test_runtime_dir="$(mktemp -d "${TMPDIR:-/tmp}/rl-learner-test.XXXXXX")"
trap 'rm -rf "${test_runtime_dir}"' EXIT
cd "${test_runtime_dir}"

# TCR-A3-TEST-BOUNDARY-001: this is the only repository test runner.
# Keep the allowlist explicit. Adding or changing a test requires an approved
# TCR before its fully-qualified case is added here.
python3 -m unittest -v \
    tests.test_chain_readiness.TrainingChainReadinessTest.test_allows_one_version_lag_with_exact_identities \
    tests.test_chain_readiness.TrainingChainReadinessTest.test_rejects_digest_or_ack_identity_mismatch \
    tests.test_chain_readiness.TrainingChainReadinessTest.test_requires_service_instances_and_pool_readiness \
    tests.test_chain_readiness.TrainingChainReadinessTest.test_requires_recent_client_activity_not_only_a_session_record \
    tests.test_chain_readiness.TrainingChainReadinessTest.test_rejects_policy_lag_outside_bound \
    tests.test_checkpoint_resume_publication.CheckpointResumePublicationTest.test_inherited_publication_loads_only_weights_and_starts_at_v0 \
    tests.test_checkpoint_resume_publication.CheckpointResumePublicationTest.test_weight_inheritance_is_one_shot_and_requires_a_fresh_trainer \
    tests.test_checkpoint_resume_publication.CheckpointResumePublicationTest.test_previous_workspace_is_never_auto_resumed \
    tests.test_checkpoint_resume_publication.CheckpointResumePublicationTest.test_initial_model_requires_an_explicit_onnx_file \
    tests.test_checkpoint_resume_publication.CheckpointResumePublicationTest.test_archive_cadence_uses_global_train_updates \
    tests.test_delivery_contract.DeliveryContractTest.test_bounded_single_version_delivery_passes \
    tests.test_delivery_contract.DeliveryContractTest.test_partial_delivery_is_accepted_only_for_explicit_final_drain \
    tests.test_delivery_contract.DeliveryContractTest.test_mixed_behavior_steps_fail_closed \
    tests.test_delivery_contract.DeliveryContractTest.test_payload_or_policy_identity_drift_fails \
    tests.test_delivery_contract.DeliveryContractTest.test_non_canonical_producer_component_fails \
    tests.test_effective_config.EffectiveConfigTest.test_default_and_allowed_ppo_overrides_resolve_for_startup \
    tests.test_effective_config.EffectiveConfigTest.test_cli_paths_and_endpoints_override_config_for_startup \
    tests.test_effective_config.EffectiveConfigTest.test_invalid_or_platform_owned_overrides_fail_before_startup \
    tests.test_effective_config.EffectiveConfigTest.test_initial_model_ack_wait_default_and_bounded_diagnostic \
    tests.test_effective_policy_lag.EffectivePolicyLagTest.test_checkpoint_restart_starts_with_lag_zero \
    tests.test_effective_policy_lag.EffectivePolicyLagTest.test_contiguous_publications_expand_to_configured_cap \
    tests.test_effective_policy_lag.EffectivePolicyLagTest.test_manifest_gap_does_not_widen_freshness \
    tests.test_effective_policy_lag.EffectivePolicyLagTest.test_contiguous_old_samples_remain_valid_after_publication \
    tests.test_effective_policy_lag.EffectivePolicyLagTest.test_unresolvable_manifest_stops_the_contiguous_window \
    tests.test_effective_policy_lag.EffectivePolicyLagTest.test_unresolvable_current_manifest_fails_before_remote_work \
    tests.test_healthcheck_contract.HealthcheckContractTest.test_optional_monitor_port_does_not_own_container_health \
    tests.test_healthcheck_contract.HealthcheckContractTest.test_training_dependency_port_failure_is_unhealthy \
    tests.test_metric_event_relay.AIServerMetricRelayTest.test_ack_is_sent_only_after_raw_batch_is_durable \
    tests.test_metric_event_relay.AIServerMetricRelayTest.test_recovered_pending_batch_is_acked_without_get \
    tests.test_metric_event_store.RawMetricBatchStoreTest.test_raw_bytes_are_durable_before_ack_and_pending_recovers \
    tests.test_metric_event_store.RawMetricBatchStoreTest.test_conflicting_replay_is_rejected_without_moving_cursor \
    tests.test_metric_event_store.RawMetricBatchStoreTest.test_zero_event_final_heartbeat_commits_event_cursor_zero \
    tests.test_metric_event_store.RawMetricBatchStoreTest.test_source_replacement_marks_unfinalized_source_incomplete \
    tests.test_metric_event_store.RawMetricBatchStoreTest.test_event_time_watermark_cannot_regress \
    tests.test_metric_event_store.RawMetricBatchStoreTest.test_local_writer_commits_exact_update_and_final_heartbeat \
    tests.test_metric_event_store.RawMetricBatchStoreTest.test_local_writer_clamps_wall_clock_rollback \
    tests.test_metric_event_store.RawMetricBatchStoreTest.test_local_writer_records_gap_and_continues_after_missing_update \
    tests.test_metrics_contract.MetricsContractTest.test_operational_training_depth_uses_the_committed_runtime_state \
    tests.test_metrics_contract.MetricsContractTest.test_actor_snapshot_projects_client_and_model_chain_state \
    tests.test_metrics_contract.MetricsContractTest.test_status_reports_one_current_metrics_source \
    tests.test_metrics_contract.MetricsContractTest.test_metrics_backend_failure_does_not_block_runtime_startup \
    tests.test_metrics_contract.MetricsContractTest.test_metric_snapshot_preserves_neutral_sample_flow_facts \
    tests.test_metrics_contract.MetricsContractTest.test_component_error_remains_task_neutral \
    tests.test_metrics_contract.MetricsContractTest.test_reader_summary_exposes_sample_and_chain_state_without_platform_id \
    tests.test_model_commit_contract.ModelCommitContractTest.test_config_is_complete_and_old_environment_alias_is_ignored \
    tests.test_model_commit_contract.ModelCommitContractTest.test_runtime_config_requires_a_bound_internal_lineage \
    tests.test_model_commit_contract.ModelCommitContractTest.test_archive_interval_uses_only_effective_config \
    tests.test_model_commit_contract.ModelCommitContractTest.test_training_identity_digest_is_canonical_and_seed_specific \
    tests.test_model_commit_contract.ModelCommitContractTest.test_prepare_rejects_unclean_local_train_data \
    tests.test_model_commit_contract.ModelCommitContractTest.test_prepare_ignores_optional_metrics_history \
    tests.test_model_commit_contract.ModelCommitContractTest.test_runtime_starts_with_metrics_path_unavailable \
    tests.test_model_commit_contract.ModelCommitContractTest.test_manifest_binds_full_identity_and_detects_corruption \
    tests.test_model_commit_contract.ModelCommitContractTest.test_canonical_publication_retains_recent_101_and_permanent_intervals \
    tests.test_model_commit_contract.ModelCommitContractTest.test_step_name_is_minimum_width_seven_without_wraparound \
    tests.test_model_commit_contract.ModelCommitContractTest.test_failed_export_leaves_no_visible_or_private_publication \
    tests.test_model_commit_contract.ModelCommitContractTest.test_prepare_recovers_only_known_private_publication_directories \
    tests.test_model_commit_contract.ModelCommitContractTest.test_state_write_failure_hides_publication_and_keeps_private_checkpoint \
    tests.test_model_commit_contract.ModelCommitContractTest.test_complete_manifest_rejects_mutated_wire_identity_and_shape \
    tests.test_ppo_contract.ModelParityTest.test_onnx_export_matches_the_pytorch_serving_outputs \
    tests.test_ppo_contract.ModelParityTest.test_actor_wire_sample_and_onnx_model_share_one_policy_binding \
    tests.test_ppo_contract.PpoUpdateTest.test_update_changes_model_once_and_exports_the_new_step \
    tests.test_ppo_contract.PpoUpdateTest.test_stale_or_non_finite_batch_does_not_mutate_the_model \
    tests.test_ppo_contract.PpoUpdateTest.test_mixed_behavior_steps_do_not_start_an_update \
    tests.test_rpc_response_coherence.RpcResponseCoherenceTest.test_leased_get_batch_requires_coherent_ready_authority_envelope \
    tests.test_rpc_response_coherence.RpcResponseCoherenceTest.test_coherent_leased_get_batch_preserves_exact_authority \
    tests.test_rpc_response_coherence.RpcResponseCoherenceTest.test_renew_lease_validates_response_before_authority_success \
    tests.test_rpc_response_coherence.RpcResponseCoherenceTest.test_lease_renewer_does_not_start_after_synchronous_authority_failure \
    tests.test_run_launcher.RunLauncherTest.test_shell_entrypoints_are_syntactically_valid \
    tests.test_run_launcher.RunLauncherTest.test_workspace_reset_clears_only_the_owned_train_directory \
    tests.test_run_launcher.RunLauncherTest.test_workspace_reset_rejects_unowned_or_symlink_roots \
    tests.test_runtime_connection_logging.RuntimeSelectionTest.test_get_batch_requests_bounded_freshness_window \
    tests.test_runtime_connection_logging.RuntimeSelectionTest.test_rejects_pool_contract_drift \
    tests.test_runtime_connection_logging.RuntimeSelectionTest.test_explicit_finalize_trains_available_tail_before_completion \
    tests.test_sample_transport_recovery.SampleTransportRecoveryTest.test_deadline_with_hidden_lease_waits_for_expiry_before_retry \
    tests.test_sample_transport_recovery.SampleTransportRecoveryTest.test_reconciliation_fails_closed_on_authority_change \
    tests.test_sample_transport_recovery.SampleTransportRecoveryTest.test_non_retryable_get_batch_transport_error_is_terminal \
    tests.test_sample_transport_recovery.SampleTransportRecoveryTest.test_sample_pool_readiness_transport_faults_wait_then_recover \
    tests.test_sample_transport_recovery.SampleTransportRecoveryTest.test_shutdown_with_stop_set_waits_out_a_hidden_lease \
    tests.test_sample_transport_recovery.SampleTransportRecoveryTest.test_shutdown_unsettled_ready_samples_is_a_failure \
    tests.test_update_transaction_recovery.UpdateTransactionRecoveryTest.test_update_publishes_registers_acks_and_emits_one_fact \
    tests.test_update_transaction_recovery.UpdateTransactionRecoveryTest.test_lease_loss_after_optimizer_rolls_back_the_update \
    tests.test_update_transaction_recovery.UpdateTransactionRecoveryTest.test_checkpoint_or_export_failure_does_not_publish_a_model \
    tests.test_update_transaction_recovery.UpdateTransactionRecoveryTest.test_bootstrap_wait_is_unbounded_until_the_exact_ack \
    tests.test_update_transaction_recovery.UpdateTransactionRecoveryTest.test_explicit_stop_ends_the_unbounded_bootstrap_wait_cleanly
