# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/metrics/catalog.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/metrics/catalog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.common import identity_pb2 as proto_dot_common_dot_identity__pb2
from proto.metrics import registry_pb2 as proto_dot_metrics_dot_registry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproto/metrics/catalog.proto\x12\x0erl.training.v1\x1a\x1bproto/common/identity.proto\x1a\x1cproto/metrics/registry.proto\"\x15\n\x13GetMetricCatalogReq\"\x93\x01\n\x12MetricCatalogEntry\x12\x34\n\ndefinition\x18\x01 \x01(\x0b\x32 .rl.training.v1.MetricDefinition\x12\x15\n\rstatus_method\x18\x02 \x01(\t\x12\x14\n\x0cstatus_field\x18\x03 \x01(\t\x12\x1a\n\x12status_count_field\x18\x04 \x01(\t\"\x81\x01\n\x13GetMetricCatalogRsp\x12\x35\n\x06source\x18\x01 \x01(\x0b\x32%.rl.common.v1.ServiceInstanceIdentity\x12\x33\n\x07\x65ntries\x18\x02 \x03(\x0b\x32\".rl.training.v1.MetricCatalogEntry2t\n\x14MetricCatalogService\x12\\\n\x10GetMetricCatalog\x12#.rl.training.v1.GetMetricCatalogReq\x1a#.rl.training.v1.GetMetricCatalogRspB\x03\x80\x01\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.metrics.catalog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\200\001\000'
  _globals['_GETMETRICCATALOGREQ']._serialized_start=106
  _globals['_GETMETRICCATALOGREQ']._serialized_end=127
  _globals['_METRICCATALOGENTRY']._serialized_start=130
  _globals['_METRICCATALOGENTRY']._serialized_end=277
  _globals['_GETMETRICCATALOGRSP']._serialized_start=280
  _globals['_GETMETRICCATALOGRSP']._serialized_end=409
  _globals['_METRICCATALOGSERVICE']._serialized_start=411
  _globals['_METRICCATALOGSERVICE']._serialized_end=527
# @@protoc_insertion_point(module_scope)
