# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.metrics import transport_pb2 as proto_dot_metrics_dot_transport__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/metrics/transport_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MetricEventServiceStub:
    """Implemented independently by each metric-event owner (AIServer and Learner).
    A retry with the same cursor returns the same batch identity until
    it is acknowledged or an explicit gap proves the requested event unavailable.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMetricBatch = channel.unary_unary(
                '/rl.training.v1.MetricEventService/GetMetricBatch',
                request_serializer=proto_dot_metrics_dot_transport__pb2.GetMetricBatchReq.SerializeToString,
                response_deserializer=proto_dot_metrics_dot_transport__pb2.GetMetricBatchRsp.FromString,
                _registered_method=True)
        self.AckMetricBatch = channel.unary_unary(
                '/rl.training.v1.MetricEventService/AckMetricBatch',
                request_serializer=proto_dot_metrics_dot_transport__pb2.AckMetricBatchReq.SerializeToString,
                response_deserializer=proto_dot_metrics_dot_transport__pb2.AckMetricBatchRsp.FromString,
                _registered_method=True)


class MetricEventServiceServicer:
    """Implemented independently by each metric-event owner (AIServer and Learner).
    A retry with the same cursor returns the same batch identity until
    it is acknowledged or an explicit gap proves the requested event unavailable.
    """

    def GetMetricBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckMetricBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetricEventServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMetricBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetricBatch,
                    request_deserializer=proto_dot_metrics_dot_transport__pb2.GetMetricBatchReq.FromString,
                    response_serializer=proto_dot_metrics_dot_transport__pb2.GetMetricBatchRsp.SerializeToString,
            ),
            'AckMetricBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.AckMetricBatch,
                    request_deserializer=proto_dot_metrics_dot_transport__pb2.AckMetricBatchReq.FromString,
                    response_serializer=proto_dot_metrics_dot_transport__pb2.AckMetricBatchRsp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rl.training.v1.MetricEventService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rl.training.v1.MetricEventService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MetricEventService:
    """Implemented independently by each metric-event owner (AIServer and Learner).
    A retry with the same cursor returns the same batch identity until
    it is acknowledged or an explicit gap proves the requested event unavailable.
    """

    @staticmethod
    def GetMetricBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.training.v1.MetricEventService/GetMetricBatch',
            proto_dot_metrics_dot_transport__pb2.GetMetricBatchReq.SerializeToString,
            proto_dot_metrics_dot_transport__pb2.GetMetricBatchRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckMetricBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.training.v1.MetricEventService/AckMetricBatch',
            proto_dot_metrics_dot_transport__pb2.AckMetricBatchReq.SerializeToString,
            proto_dot_metrics_dot_transport__pb2.AckMetricBatchRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
