# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x0crl.common.v1\"N\n\rContentDigest\x12\x30\n\talgorithm\x18\x01 \x01(\x0e\x32\x1d.rl.common.v1.DigestAlgorithm\x12\x0b\n\x03hex\x18\x02 \x01(\t\"\xd9\x01\n\x10\x43ontractIdentity\x12\x14\n\x0cpackage_name\x18\x01 \x01(\t\x12\x17\n\x0fpackage_version\x18\x02 \x01(\t\x12\x32\n\rsource_digest\x18\x03 \x01(\x0b\x32\x1b.rl.common.v1.ContentDigest\x12\x34\n\x0f\x61rtifact_digest\x18\x04 \x01(\x0b\x32\x1b.rl.common.v1.ContentDigest\x12\x10\n\x08platform\x18\x05 \x01(\t\x12\x1a\n\x12generator_identity\x18\x06 \x01(\t\"r\n\x0eSchemaIdentity\x12\x11\n\tschema_id\x18\x01 \x01(\t\x12\x16\n\x0eschema_version\x18\x02 \x01(\r\x12\x35\n\x10\x63\x61nonical_digest\x18\x03 \x01(\x0b\x32\x1b.rl.common.v1.ContentDigest\"Z\n\x17ServiceInstanceIdentity\x12\x11\n\tcomponent\x18\x01 \x01(\t\x12\x13\n\x0binstance_id\x18\x02 \x01(\t\x12\x17\n\x0flifecycle_epoch\x18\x03 \x01(\x04*\x96\x01\n\x0fOperationResult\x12 \n\x1cOPERATION_RESULT_UNSPECIFIED\x10\x00\x12\x1c\n\x18OPERATION_RESULT_APPLIED\x10\x01\x12$\n OPERATION_RESULT_ALREADY_APPLIED\x10\x02\x12\x1d\n\x19OPERATION_RESULT_REJECTED\x10\x03*P\n\x0f\x44igestAlgorithm\x12 \n\x1c\x44IGEST_ALGORITHM_UNSPECIFIED\x10\x00\x12\x1b\n\x17\x44IGEST_ALGORITHM_SHA256\x10\x01\x42\x03\x80\x01\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\200\001\000'
  _globals['_OPERATIONRESULT']._serialized_start=539
  _globals['_OPERATIONRESULT']._serialized_end=689
  _globals['_DIGESTALGORITHM']._serialized_start=691
  _globals['_DIGESTALGORITHM']._serialized_end=771
  _globals['_CONTENTDIGEST']._serialized_start=30
  _globals['_CONTENTDIGEST']._serialized_end=108
  _globals['_CONTRACTIDENTITY']._serialized_start=111
  _globals['_CONTRACTIDENTITY']._serialized_end=328
  _globals['_SCHEMAIDENTITY']._serialized_start=330
  _globals['_SCHEMAIDENTITY']._serialized_end=444
  _globals['_SERVICEINSTANCEIDENTITY']._serialized_start=446
  _globals['_SERVICEINSTANCEIDENTITY']._serialized_end=536
# @@protoc_insertion_point(module_scope)
