# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x0crl.common.v1\"Z\n\x17ServiceInstanceIdentity\x12\x11\n\tcomponent\x18\x01 \x01(\t\x12\x13\n\x0binstance_id\x18\x02 \x01(\t\x12\x17\n\x0flifecycle_epoch\x18\x03 \x01(\x04*\x96\x01\n\x0fOperationResult\x12 \n\x1cOPERATION_RESULT_UNSPECIFIED\x10\x00\x12\x1c\n\x18OPERATION_RESULT_APPLIED\x10\x01\x12$\n OPERATION_RESULT_ALREADY_APPLIED\x10\x02\x12\x1d\n\x19OPERATION_RESULT_REJECTED\x10\x03\x42\x03\x80\x01\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\200\001\000'
  _globals['_OPERATIONRESULT']._serialized_start=123
  _globals['_OPERATIONRESULT']._serialized_end=273
  _globals['_SERVICEINSTANCEIDENTITY']._serialized_start=30
  _globals['_SERVICEINSTANCEIDENTITY']._serialized_end=120
# @@protoc_insertion_point(module_scope)
