# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: maze_metrics.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'maze_metrics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import training_pb2 as training__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12maze_metrics.proto\x12\x17rl.task.maze.metrics.v1\x1a\x0etraining.proto\"\x92\x05\n\x16\x41gentEpisodeMetricFact\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\r\x12\x16\n\x0e\x65pisode_return\x18\x02 \x01(\x01\x12\x18\n\x10transition_count\x18\x03 \x01(\x04\x12\x0f\n\x07success\x18\x04 \x01(\x08\x12\x1a\n\x12termination_reason\x18\x05 \x01(\t\x12\x1d\n\x15shortest_action_steps\x18\x06 \x01(\r\x12\x19\n\x11unique_cell_count\x18\x07 \x01(\x04\x12\x1a\n\x12\x62locked_move_count\x18\x08 \x01(\x04\x12\x1c\n\x14\x61ttempted_move_count\x18\t \x01(\x04\x12<\n\x11reward_components\x18\n \x03(\x0b\x32!.rl.training.v1.RawMetricSumCount\x12(\n\x1bminimum_behavior_model_step\x18\x0b \x01(\x04H\x00\x88\x01\x01\x12(\n\x1bmaximum_behavior_model_step\x18\x0c \x01(\x04H\x01\x88\x01\x01\x12!\n\x19\x62\x65havior_model_lineage_id\x18\r \x01(\t\x12\x1e\n\x11terminal_frame_id\x18\x0e \x01(\x04H\x02\x88\x01\x01\x12\x1c\n\x0fgoal_rank_group\x18\x0f \x01(\rH\x03\x88\x01\x01\x42\x1e\n\x1c_minimum_behavior_model_stepB\x1e\n\x1c_maximum_behavior_model_stepB\x14\n\x12_terminal_frame_idB\x12\n\x10_goal_rank_groupR\x1a\x62\x65havior_model_version_minR\x1a\x62\x65havior_model_version_max\"\xb8\x01\n\x11\x45pisodeMetricFact\x12\x1f\n\x17\x65nvironment_instance_id\x18\x02 \x01(\t\x12\x12\n\nepisode_id\x18\x03 \x01(\t\x12?\n\x06\x61gents\x18\x05 \x03(\x0b\x32/.rl.task.maze.metrics.v1.AgentEpisodeMetricFactJ\x04\x08\x01\x10\x02J\x04\x08\x04\x10\x05R\x07task_idR\x18training_contract_digestB\x03\x80\x01\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'maze_metrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\200\001\000'
  _globals['_AGENTEPISODEMETRICFACT']._serialized_start=64
  _globals['_AGENTEPISODEMETRICFACT']._serialized_end=722
  _globals['_EPISODEMETRICFACT']._serialized_start=725
  _globals['_EPISODEMETRICFACT']._serialized_end=909
# @@protoc_insertion_point(module_scope)
