# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import maze_task_pb2 as maze__task__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in maze_task_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MazeTaskServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OpenSession = channel.unary_unary(
                '/rl.task.maze.v1.MazeTaskService/OpenSession',
                request_serializer=maze__task__pb2.OpenSessionReq.SerializeToString,
                response_deserializer=maze__task__pb2.OpenSessionRsp.FromString,
                _registered_method=True)
        self.Init = channel.unary_unary(
                '/rl.task.maze.v1.MazeTaskService/Init',
                request_serializer=maze__task__pb2.InitReq.SerializeToString,
                response_deserializer=maze__task__pb2.InitRsp.FromString,
                _registered_method=True)
        self.BeginEpisode = channel.unary_unary(
                '/rl.task.maze.v1.MazeTaskService/BeginEpisode',
                request_serializer=maze__task__pb2.BeginEpisodeReq.SerializeToString,
                response_deserializer=maze__task__pb2.BeginEpisodeRsp.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/rl.task.maze.v1.MazeTaskService/Update',
                request_serializer=maze__task__pb2.UpdateReq.SerializeToString,
                response_deserializer=maze__task__pb2.UpdateRsp.FromString,
                _registered_method=True)
        self.EndEpisode = channel.unary_unary(
                '/rl.task.maze.v1.MazeTaskService/EndEpisode',
                request_serializer=maze__task__pb2.EndEpisodeReq.SerializeToString,
                response_deserializer=maze__task__pb2.EndEpisodeRsp.FromString,
                _registered_method=True)
        self.AbortEpisode = channel.unary_unary(
                '/rl.task.maze.v1.MazeTaskService/AbortEpisode',
                request_serializer=maze__task__pb2.AbortEpisodeReq.SerializeToString,
                response_deserializer=maze__task__pb2.AbortEpisodeRsp.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/rl.task.maze.v1.MazeTaskService/CloseSession',
                request_serializer=maze__task__pb2.CloseSessionReq.SerializeToString,
                response_deserializer=maze__task__pb2.CloseSessionRsp.FromString,
                _registered_method=True)


class MazeTaskServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def OpenSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginEpisode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndEpisode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortEpisode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MazeTaskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OpenSession': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenSession,
                    request_deserializer=maze__task__pb2.OpenSessionReq.FromString,
                    response_serializer=maze__task__pb2.OpenSessionRsp.SerializeToString,
            ),
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=maze__task__pb2.InitReq.FromString,
                    response_serializer=maze__task__pb2.InitRsp.SerializeToString,
            ),
            'BeginEpisode': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginEpisode,
                    request_deserializer=maze__task__pb2.BeginEpisodeReq.FromString,
                    response_serializer=maze__task__pb2.BeginEpisodeRsp.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=maze__task__pb2.UpdateReq.FromString,
                    response_serializer=maze__task__pb2.UpdateRsp.SerializeToString,
            ),
            'EndEpisode': grpc.unary_unary_rpc_method_handler(
                    servicer.EndEpisode,
                    request_deserializer=maze__task__pb2.EndEpisodeReq.FromString,
                    response_serializer=maze__task__pb2.EndEpisodeRsp.SerializeToString,
            ),
            'AbortEpisode': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortEpisode,
                    request_deserializer=maze__task__pb2.AbortEpisodeReq.FromString,
                    response_serializer=maze__task__pb2.AbortEpisodeRsp.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=maze__task__pb2.CloseSessionReq.FromString,
                    response_serializer=maze__task__pb2.CloseSessionRsp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rl.task.maze.v1.MazeTaskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rl.task.maze.v1.MazeTaskService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MazeTaskService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OpenSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.task.maze.v1.MazeTaskService/OpenSession',
            maze__task__pb2.OpenSessionReq.SerializeToString,
            maze__task__pb2.OpenSessionRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.task.maze.v1.MazeTaskService/Init',
            maze__task__pb2.InitReq.SerializeToString,
            maze__task__pb2.InitRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BeginEpisode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.task.maze.v1.MazeTaskService/BeginEpisode',
            maze__task__pb2.BeginEpisodeReq.SerializeToString,
            maze__task__pb2.BeginEpisodeRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.task.maze.v1.MazeTaskService/Update',
            maze__task__pb2.UpdateReq.SerializeToString,
            maze__task__pb2.UpdateRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndEpisode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.task.maze.v1.MazeTaskService/EndEpisode',
            maze__task__pb2.EndEpisodeReq.SerializeToString,
            maze__task__pb2.EndEpisodeRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortEpisode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.task.maze.v1.MazeTaskService/AbortEpisode',
            maze__task__pb2.AbortEpisodeReq.SerializeToString,
            maze__task__pb2.AbortEpisodeRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.task.maze.v1.MazeTaskService/CloseSession',
            maze__task__pb2.CloseSessionReq.SerializeToString,
            maze__task__pb2.CloseSessionRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
