# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import training_pb2 as training__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in training_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServerTrainingStatusServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAIServerStatus = channel.unary_unary(
                '/rl.training.v1.AIServerTrainingStatusService/GetAIServerStatus',
                request_serializer=training__pb2.AIServerStatusReq.SerializeToString,
                response_deserializer=training__pb2.AIServerStatusRsp.FromString,
                _registered_method=True)


class AIServerTrainingStatusServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetAIServerStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServerTrainingStatusServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAIServerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAIServerStatus,
                    request_deserializer=training__pb2.AIServerStatusReq.FromString,
                    response_serializer=training__pb2.AIServerStatusRsp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rl.training.v1.AIServerTrainingStatusService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rl.training.v1.AIServerTrainingStatusService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIServerTrainingStatusService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAIServerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.training.v1.AIServerTrainingStatusService/GetAIServerStatus',
            training__pb2.AIServerStatusReq.SerializeToString,
            training__pb2.AIServerStatusRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MetricEventServiceStub:
    """Implemented independently by each metric-event owner (AIServer and Learner).
    A retry with the same cursor returns the same batch identity and digest until
    it is acknowledged or an explicit gap proves the requested event unavailable.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMetricBatch = channel.unary_unary(
                '/rl.training.v1.MetricEventService/GetMetricBatch',
                request_serializer=training__pb2.GetMetricBatchReq.SerializeToString,
                response_deserializer=training__pb2.GetMetricBatchRsp.FromString,
                _registered_method=True)
        self.AckMetricBatch = channel.unary_unary(
                '/rl.training.v1.MetricEventService/AckMetricBatch',
                request_serializer=training__pb2.AckMetricBatchReq.SerializeToString,
                response_deserializer=training__pb2.AckMetricBatchRsp.FromString,
                _registered_method=True)


class MetricEventServiceServicer:
    """Implemented independently by each metric-event owner (AIServer and Learner).
    A retry with the same cursor returns the same batch identity and digest until
    it is acknowledged or an explicit gap proves the requested event unavailable.
    """

    def GetMetricBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckMetricBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetricEventServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMetricBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetricBatch,
                    request_deserializer=training__pb2.GetMetricBatchReq.FromString,
                    response_serializer=training__pb2.GetMetricBatchRsp.SerializeToString,
            ),
            'AckMetricBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.AckMetricBatch,
                    request_deserializer=training__pb2.AckMetricBatchReq.FromString,
                    response_serializer=training__pb2.AckMetricBatchRsp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rl.training.v1.MetricEventService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rl.training.v1.MetricEventService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MetricEventService:
    """Implemented independently by each metric-event owner (AIServer and Learner).
    A retry with the same cursor returns the same batch identity and digest until
    it is acknowledged or an explicit gap proves the requested event unavailable.
    """

    @staticmethod
    def GetMetricBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.training.v1.MetricEventService/GetMetricBatch',
            training__pb2.GetMetricBatchReq.SerializeToString,
            training__pb2.GetMetricBatchRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckMetricBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.training.v1.MetricEventService/AckMetricBatch',
            training__pb2.AckMetricBatchReq.SerializeToString,
            training__pb2.AckMetricBatchRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LearnerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendSamples = channel.unary_unary(
                '/rl.training.v1.LearnerService/SendSamples',
                request_serializer=training__pb2.SampleBatch.SerializeToString,
                response_deserializer=training__pb2.SampleResponse.FromString,
                _registered_method=True)


class LearnerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def SendSamples(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LearnerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendSamples': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSamples,
                    request_deserializer=training__pb2.SampleBatch.FromString,
                    response_serializer=training__pb2.SampleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rl.training.v1.LearnerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rl.training.v1.LearnerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LearnerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendSamples(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.training.v1.LearnerService/SendSamples',
            training__pb2.SampleBatch.SerializeToString,
            training__pb2.SampleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SampleDistributorServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpsertSampleDemand = channel.unary_unary(
                '/rl.training.v1.SampleDistributorService/UpsertSampleDemand',
                request_serializer=training__pb2.UpsertSampleDemandReq.SerializeToString,
                response_deserializer=training__pb2.SampleDemandRsp.FromString,
                _registered_method=True)
        self.ReleaseSampleDemand = channel.unary_unary(
                '/rl.training.v1.SampleDistributorService/ReleaseSampleDemand',
                request_serializer=training__pb2.ReleaseSampleDemandReq.SerializeToString,
                response_deserializer=training__pb2.SampleDemandRsp.FromString,
                _registered_method=True)
        self.GetSampleDemandStatus = channel.unary_unary(
                '/rl.training.v1.SampleDistributorService/GetSampleDemandStatus',
                request_serializer=training__pb2.GetSampleDemandStatusReq.SerializeToString,
                response_deserializer=training__pb2.SampleDemandStatusRsp.FromString,
                _registered_method=True)
        self.AcquireSampleCredit = channel.unary_unary(
                '/rl.training.v1.SampleDistributorService/AcquireSampleCredit',
                request_serializer=training__pb2.AcquireSampleCreditReq.SerializeToString,
                response_deserializer=training__pb2.SampleCreditGrant.FromString,
                _registered_method=True)
        self.ReleaseSampleCredit = channel.unary_unary(
                '/rl.training.v1.SampleDistributorService/ReleaseSampleCredit',
                request_serializer=training__pb2.ReleaseSampleCreditReq.SerializeToString,
                response_deserializer=training__pb2.ReleaseSampleCreditRsp.FromString,
                _registered_method=True)
        self.PushSamples = channel.unary_unary(
                '/rl.training.v1.SampleDistributorService/PushSamples',
                request_serializer=training__pb2.PushSamplesReq.SerializeToString,
                response_deserializer=training__pb2.PushSamplesRsp.FromString,
                _registered_method=True)
        self.GetBatch = channel.unary_unary(
                '/rl.training.v1.SampleDistributorService/GetBatch',
                request_serializer=training__pb2.GetBatchReq.SerializeToString,
                response_deserializer=training__pb2.GetBatchRsp.FromString,
                _registered_method=True)
        self.AckBatch = channel.unary_unary(
                '/rl.training.v1.SampleDistributorService/AckBatch',
                request_serializer=training__pb2.AckBatchReq.SerializeToString,
                response_deserializer=training__pb2.DeliveryRsp.FromString,
                _registered_method=True)
        self.NackBatch = channel.unary_unary(
                '/rl.training.v1.SampleDistributorService/NackBatch',
                request_serializer=training__pb2.NackBatchReq.SerializeToString,
                response_deserializer=training__pb2.DeliveryRsp.FromString,
                _registered_method=True)
        self.RenewLease = channel.unary_unary(
                '/rl.training.v1.SampleDistributorService/RenewLease',
                request_serializer=training__pb2.RenewLeaseReq.SerializeToString,
                response_deserializer=training__pb2.DeliveryRsp.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/rl.training.v1.SampleDistributorService/GetStatus',
                request_serializer=training__pb2.DistributorStatusReq.SerializeToString,
                response_deserializer=training__pb2.DistributorStatusRsp.FromString,
                _registered_method=True)


class SampleDistributorServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def UpsertSampleDemand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseSampleDemand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSampleDemandStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcquireSampleCredit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseSampleCredit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushSamples(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NackBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SampleDistributorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpsertSampleDemand': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertSampleDemand,
                    request_deserializer=training__pb2.UpsertSampleDemandReq.FromString,
                    response_serializer=training__pb2.SampleDemandRsp.SerializeToString,
            ),
            'ReleaseSampleDemand': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseSampleDemand,
                    request_deserializer=training__pb2.ReleaseSampleDemandReq.FromString,
                    response_serializer=training__pb2.SampleDemandRsp.SerializeToString,
            ),
            'GetSampleDemandStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSampleDemandStatus,
                    request_deserializer=training__pb2.GetSampleDemandStatusReq.FromString,
                    response_serializer=training__pb2.SampleDemandStatusRsp.SerializeToString,
            ),
            'AcquireSampleCredit': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquireSampleCredit,
                    request_deserializer=training__pb2.AcquireSampleCreditReq.FromString,
                    response_serializer=training__pb2.SampleCreditGrant.SerializeToString,
            ),
            'ReleaseSampleCredit': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseSampleCredit,
                    request_deserializer=training__pb2.ReleaseSampleCreditReq.FromString,
                    response_serializer=training__pb2.ReleaseSampleCreditRsp.SerializeToString,
            ),
            'PushSamples': grpc.unary_unary_rpc_method_handler(
                    servicer.PushSamples,
                    request_deserializer=training__pb2.PushSamplesReq.FromString,
                    response_serializer=training__pb2.PushSamplesRsp.SerializeToString,
            ),
            'GetBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBatch,
                    request_deserializer=training__pb2.GetBatchReq.FromString,
                    response_serializer=training__pb2.GetBatchRsp.SerializeToString,
            ),
            'AckBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.AckBatch,
                    request_deserializer=training__pb2.AckBatchReq.FromString,
                    response_serializer=training__pb2.DeliveryRsp.SerializeToString,
            ),
            'NackBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.NackBatch,
                    request_deserializer=training__pb2.NackBatchReq.FromString,
                    response_serializer=training__pb2.DeliveryRsp.SerializeToString,
            ),
            'RenewLease': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewLease,
                    request_deserializer=training__pb2.RenewLeaseReq.FromString,
                    response_serializer=training__pb2.DeliveryRsp.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=training__pb2.DistributorStatusReq.FromString,
                    response_serializer=training__pb2.DistributorStatusRsp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rl.training.v1.SampleDistributorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rl.training.v1.SampleDistributorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SampleDistributorService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpsertSampleDemand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.training.v1.SampleDistributorService/UpsertSampleDemand',
            training__pb2.UpsertSampleDemandReq.SerializeToString,
            training__pb2.SampleDemandRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseSampleDemand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.training.v1.SampleDistributorService/ReleaseSampleDemand',
            training__pb2.ReleaseSampleDemandReq.SerializeToString,
            training__pb2.SampleDemandRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSampleDemandStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.training.v1.SampleDistributorService/GetSampleDemandStatus',
            training__pb2.GetSampleDemandStatusReq.SerializeToString,
            training__pb2.SampleDemandStatusRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcquireSampleCredit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.training.v1.SampleDistributorService/AcquireSampleCredit',
            training__pb2.AcquireSampleCreditReq.SerializeToString,
            training__pb2.SampleCreditGrant.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseSampleCredit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.training.v1.SampleDistributorService/ReleaseSampleCredit',
            training__pb2.ReleaseSampleCreditReq.SerializeToString,
            training__pb2.ReleaseSampleCreditRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushSamples(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.training.v1.SampleDistributorService/PushSamples',
            training__pb2.PushSamplesReq.SerializeToString,
            training__pb2.PushSamplesRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.training.v1.SampleDistributorService/GetBatch',
            training__pb2.GetBatchReq.SerializeToString,
            training__pb2.GetBatchRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.training.v1.SampleDistributorService/AckBatch',
            training__pb2.AckBatchReq.SerializeToString,
            training__pb2.DeliveryRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NackBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.training.v1.SampleDistributorService/NackBatch',
            training__pb2.NackBatchReq.SerializeToString,
            training__pb2.DeliveryRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenewLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.training.v1.SampleDistributorService/RenewLease',
            training__pb2.RenewLeaseReq.SerializeToString,
            training__pb2.DeliveryRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.training.v1.SampleDistributorService/GetStatus',
            training__pb2.DistributorStatusReq.SerializeToString,
            training__pb2.DistributorStatusRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ModelDistributorServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterModel = channel.unary_unary(
                '/rl.training.v1.ModelDistributorService/RegisterModel',
                request_serializer=training__pb2.RegisterModelReq.SerializeToString,
                response_deserializer=training__pb2.RegisterModelRsp.FromString,
                _registered_method=True)
        self.GetModelManifest = channel.unary_unary(
                '/rl.training.v1.ModelDistributorService/GetModelManifest',
                request_serializer=training__pb2.GetModelManifestReq.SerializeToString,
                response_deserializer=training__pb2.GetModelManifestRsp.FromString,
                _registered_method=True)
        self.DownloadModel = channel.unary_stream(
                '/rl.training.v1.ModelDistributorService/DownloadModel',
                request_serializer=training__pb2.DownloadModelReq.SerializeToString,
                response_deserializer=training__pb2.ModelChunk.FromString,
                _registered_method=True)
        self.AckModel = channel.unary_unary(
                '/rl.training.v1.ModelDistributorService/AckModel',
                request_serializer=training__pb2.AckModelReq.SerializeToString,
                response_deserializer=training__pb2.AckModelRsp.FromString,
                _registered_method=True)
        self.GetModelDistributorStatus = channel.unary_unary(
                '/rl.training.v1.ModelDistributorService/GetModelDistributorStatus',
                request_serializer=training__pb2.ModelDistributorStatusReq.SerializeToString,
                response_deserializer=training__pb2.ModelDistributorStatusRsp.FromString,
                _registered_method=True)


class ModelDistributorServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RegisterModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelManifest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelDistributorStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelDistributorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterModel': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterModel,
                    request_deserializer=training__pb2.RegisterModelReq.FromString,
                    response_serializer=training__pb2.RegisterModelRsp.SerializeToString,
            ),
            'GetModelManifest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelManifest,
                    request_deserializer=training__pb2.GetModelManifestReq.FromString,
                    response_serializer=training__pb2.GetModelManifestRsp.SerializeToString,
            ),
            'DownloadModel': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadModel,
                    request_deserializer=training__pb2.DownloadModelReq.FromString,
                    response_serializer=training__pb2.ModelChunk.SerializeToString,
            ),
            'AckModel': grpc.unary_unary_rpc_method_handler(
                    servicer.AckModel,
                    request_deserializer=training__pb2.AckModelReq.FromString,
                    response_serializer=training__pb2.AckModelRsp.SerializeToString,
            ),
            'GetModelDistributorStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelDistributorStatus,
                    request_deserializer=training__pb2.ModelDistributorStatusReq.FromString,
                    response_serializer=training__pb2.ModelDistributorStatusRsp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rl.training.v1.ModelDistributorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rl.training.v1.ModelDistributorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelDistributorService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.training.v1.ModelDistributorService/RegisterModel',
            training__pb2.RegisterModelReq.SerializeToString,
            training__pb2.RegisterModelRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelManifest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.training.v1.ModelDistributorService/GetModelManifest',
            training__pb2.GetModelManifestReq.SerializeToString,
            training__pb2.GetModelManifestRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rl.training.v1.ModelDistributorService/DownloadModel',
            training__pb2.DownloadModelReq.SerializeToString,
            training__pb2.ModelChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.training.v1.ModelDistributorService/AckModel',
            training__pb2.AckModelReq.SerializeToString,
            training__pb2.AckModelRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelDistributorStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.training.v1.ModelDistributorService/GetModelDistributorStatus',
            training__pb2.ModelDistributorStatusReq.SerializeToString,
            training__pb2.ModelDistributorStatusRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
