# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/training/model_identity.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/training/model_identity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#proto/training/model_identity.proto\x12\x0erl.training.v1\"\x8e\x01\n\rModelIdentity\x12\x18\n\x10model_lineage_id\x18\x01 \x01(\t\x12\x17\n\nmodel_step\x18\x02 \x01(\x04H\x00\x88\x01\x01\x42\r\n\x0b_model_stepJ\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05R\rmodel_versionR\x0f\x61rtifact_digestR\x0fmanifest_digestB\x03\x80\x01\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.training.model_identity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\200\001\000'
  _globals['_MODELIDENTITY']._serialized_start=56
  _globals['_MODELIDENTITY']._serialized_end=198
# @@protoc_insertion_point(module_scope)
